version: '3'

services:
  server:
    build: .
    container_name: backend
    ports:
      - "8080:8080"
    depends_on:
      - "db"
  db:
    image: "mongo"
    container_name: "database"
    volumes:
      - "db-data:/data"

volumes:
  db-data: